Repository Screwloose-Games/godot-wild-jam-77, pull requests merged in 2025-01, with the labels that each got.

#66 Create sm_altar.fbx
  raw_assets/models/sm_altar.fbx
Labels: art, env, interactives, Blocking

#70 WIP Trees/log
  raw_assets/models/Foliage/sm_log1.fbx
  raw_assets/models/Foliage/sm_tree1.fbx
  raw_assets/models/Foliage/sm_tree2.fbx
  raw_assets/models/Foliage/sm_tree3.fbx
Labels: art, env, 3d model

#103 add title.svg, ring.svg
  common/ui/main_menu/title.svg
  common/ui/options_menu/ring.svg
  common/ui/pause_menu/ring.svg
Labels: art, ui

#122 Finalize terrain mesh to start building world and gameplay
  game/levels/Environments/crater_walls.bin
  game/levels/Environments/crater_walls.gltf
  game/levels/Environments/crater_walls.gltf.import
  game/levels/Environments/greybox.blend
  game/levels/Environments/terrain.bin
  game/levels/Environments/terrain.gltf
  game/levels/Environments/terrain.gltf.import
Labels: art, env, Blocking

#124 Configure Inherited Scene & Configure Advanced Import Settings
  game/levels/Environments/sm_crater_walls.gltf
  game/levels/Environments/sm_crater_walls.gltf.import
  game/levels/Environments/sm_crater_walls.tscn
  game/levels/Environments/sm_terrain.gltf
  game/levels/Environments/sm_terrain.gltf.import
  game/levels/Environments/sm_terrain.tscn
Labels: implementation

#125 Add f button interactive display, clean up naming convention for merged assets (add "tex_" and reimport)
  common/ui/main_menu/tex_title.svg
  common/ui/main_menu/tex_title.svg.import
  common/ui/options_menu/tex_ring.svg
  common/ui/options_menu/tex_ring.svg.import
  common/ui/pause_menu/tex_ring.svg
  common/ui/pause_menu/tex_ring.svg.import
  game/altar/tex_press_f_pressed.svg
  game/altar/tex_press_f_pressed.svg.import
  game/altar/tex_press_f_static.svg
  game/altar/tex_press_f_static.svg.import
Labels: art, interactives

#134 add terrain textures, terrain .blend file, .gltf file
  game/levels/Environments/sm_meda_terrain.bin
  game/levels/Environments/sm_meda_terrain.gltf
  game/levels/Environments/sm_meda_terrain.gltf.import
  game/levels/Environments/tex_grass_1.png
  game/levels/Environments/tex_grass_1.png.import
  game/levels/meda_terrain.blend
  game/terrain/ground/tex_rock_2.png
  game/terrain/ground/tex_rock_2.png.import
  game/terrain/ground/tex_rock_3.png
  game/terrain/ground/tex_rock_3.png.import
  game/terrain/ground/tex_rock_4.png
  game/terrain/ground/tex_rock_4.png.import
  game/terrain/ground/tex_rock_5.png
  game/terrain/ground/tex_rock_5.png.import
  game/terrain/ground/tex_stone_1.png
  game/terrain/ground/tex_stone_1.png.import
  game/terrain/ground/tex_stone_2.png
  game/terrain/ground/tex_stone_2.png.import
Labels: art, env, Blocking

#144 update terrain size to more closely match intended scale
  game/levels/level_01/sm_meda_terrain.bin
  game/levels/level_01/sm_meda_terrain.gltf
  game/levels/meda_terrain.blend
Labels: art, env

#146 update meda_terrain . blend file to match intended scale
  game/levels/level_01/sm_meda_terrain.bin
  game/levels/level_01/sm_meda_terrain.gltf
  game/levels/level_01/textures/tex_rock_3.png
  game/levels/level_01/textures/tex_rock_3.png.import
  game/levels/meda_terrain.blend
  game/levels/meda_terrain.blend1
Labels: art, env

#166 delete duplicate env from lvl_01_env scene, add texture to tree gate,…
  game/gateway/sm_tree_gate.bin
  game/gateway/sm_tree_gate.gltf
  game/gateway/sm_tree_gate.gltf.import
  game/gateway/sm_treegate1.glb
  game/gateway/sm_treegate1.glb.import
  game/gateway/sm_treegate1_aap-64-gradient.png.import
  game/gateway/textures/tex_tree_2.png
  game/gateway/textures/tex_tree_2.png.import
  game/levels/level_01/lvl_01_environment.tscn
Labels: art, env

#167 Enabled Physics and collision for trees
  game/levels/level_01/sm_meda_terrain.gltf.import
  game/levels/level_01/sm_meda_terrain_objects.gltf.import
  test/test_altar_locations/test_melee_altar_location.tscn
Labels: bug, implementation
